export const API_ROOT = "http://localhost:8080/api/v1";
export const ROLE = {
  ADMIN: "ADMIN",
  CUSTOMER: "CUSTOMER",
  VETERINARIAN: "VETERINARIAN",
  STAFF: "STAFF",
};
export const BOOKING_TYPE = {
  ONLINE: "ONLINE",
  HOME: "HOME",
  CENTER: "CENTER",
};

export const APPOINTMENT_STATUS = {
  CREATED: "CREATED", 
  BOOKING_COMPLETE: "BOOKING_COMPLETE", 
  PROCESS: "PROCESS",
  READY_FOR_PAYMENT: "READY_FOR_PAYMENT",
  FINISH: "FINISH",
  CANCEL: "CANCEL"
};

export const SERVICE_FOR = {
  KOI: "FISH",
  POND: "POND",
};

